#!/bin/sh

if [ $# -lt 1 ]; then
    echo "\nOption Required"
    echo " --start : to start soundhook"
    echo " --stop  : to stop  soundhook"
    echo " --state : to check soundhook status\n"
    exit;
fi

if [ $1 = '--restart' ]; then
    echo "RESTARTING..."
    sleep 1s
    sh soundhook --stop
    sleep 1s
    sh soundhook --start
    sleep 1s
elif [ $1 = '--start' ]; then
    dir=`date "+%Y"`
    if [ ! -e log/$dir ]; then
      mkdir log/$dir
    fi
    f_path=log/$dir/`date "+%m%d"`.log
    nohup sh   $PWD/cron_set/watcher.sh >  log/watcher.log &
    nohup sh   $PWD/cron_set/cron.sh    >  log/cron.log    &
    nohup node $PWD/app.js              >> $f_path         &

    sleep 1s
    echo "\n\n -- now starting SoundHook :)\n\n"
    exit
elif [ $1 = '--state' ]; then
    echo `ps aux | grep $PWD/cron_set/watcher.sh    | grep -v grep`
    echo `ps aux | grep $PWD/cron_set/cron.sh       | grep -v grep`
    echo `ps aux | grep $PWD/app.js                 | grep -v grep`
    exit;
elif [ $1 = '--stop' ]; then
    kill -9 `ps aux | grep $PWD/cron_set/watcher.sh | grep -v grep | awk {'print $2'}`
    kill -9 `ps aux | grep $PWD/cron_set/cron.sh    | grep -v grep | awk {'print $2'}`
    kill -9 `ps aux | grep $PWD/app.js              | grep -v grep | awk {'print $2'}`
    sleep 1s
    echo "\n\n -- now stoped SoundHook \n\n"
    exit;
elif [ $1 = '--help' ]; then
    echo " Options\n"
    echo "  --start"
    echo "  --state"
    #echo "  --restart"
    echo "  --stop\n"
else
    echo "illeagal option\n"
fi

